language: go

go:
  - "1.14.x"
  - "1.15.x"

services:
  - docker

before_install:
  - docker pull redis
  - go get -t -v ./...

env:
  - GO111MODULE=on
script:
  -  ./go_test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
